server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javscript,application/javascript,application/json
    min-reponse-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4

spring:
  datasource:
    url: jdbc:mysql://localhost:33600/productdb
    username: root
    password: root
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000 # para segurança
      maximum-pool-size: 20 # o ideal é manter baixo
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  properties:
    "[hibernates.dialect]": org.hibernate.dialect.MySQL5InnoDBDialect
    "[hibernates.generate_statistics]": false
    "[hibernates.connection.provider_disables_autocommit]": true